name: flutter-project
description: "A new Flutter project."
Author: "Sconl Peter | Ace Cyber Space"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_central_dependency:
    git:
      url: git@github.com:Sconl/flutter-central-dependency.git
      ref: tags/v1.0.0  # Replace with the desired version tag (optional)

dev_dependencies:
  flutter_lints: ^3.0.1
  lints: 3.0.0
  flutter_test:
    sdk: flutter
  flame_test: ^1.16.0
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
