name: test_widget
description: A package for conducting tests in my flutter projects
version: 0.0.1
publish_to: "none"
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_central_dependency:
    git:
      url: git@github.com:Sconl/flutter-central-dependency.git

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
